apiVersion: v1
kind: ReplicationController
metadata:
  name: kuber-r-ctr
spec:
  replicas: 3
  selector:
    app: kuber-r-ctr
  template:
    metadata:
      name: kuber-r-ctr
      labels:
        app: kuber-r-ctr
    spec:
      containers:
        - name: kuber-r-ctr
          image: bakavets/kuber:v1.0
          ports:
            - containerPort: 8000
