apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
  labels:
    app: test-app
    environment: dev
spec:
  containers:
  - name: test-app-container
    image: bakavets/kuber:v1.0
    ports:
    - containerPort: 8000